name: build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - run: nuget restore source/Contact-Conversion-Wizard.sln
    - run: dotnet build source/Contact-Conversion-Wizard.sln --configuration Release --framework net40
    - run: cd source/bin/Release/ && dir && cd
