name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.5.1'
    - run: dotnet build source/Contact-Conversion-Wizard.sln --configuration Release --framework net40
    - run: cd source/bin/Release/ && dir
